---
# ./main.yml
- hosts: all
  tasks:
    - debug:
        msg: Install OpenLDAP

    - name: install OpenLDAP
      import_tasks: /root/ansible-ldap/tasks/ldapserver.yml
  
    - debug:
        msg: Install OpenLDAP Client

    - name: install OpenLDAP Client
      import_tasks: /root/ansible-ldap/tasks/ldapclient.yml

